const POCKET_BLOGPOSTS = "blogposts"
const POCKET_ZENDESKUSER_DISCORDUSER = "zendeskuser_discorduser"
const POCKET_SLA_BREACHING_SOON = "nearing_sla_breach_notified"
const DISCORD_API_ENDPOINT = "https://zen.jkim.win/api/discord/send-dm/";
// const DISCORD_API_ENDPOINT = "http://localhost:3000/api/discord/send-dm/";
const ZENDESK_API_ENDPOINT = "https://yaksa.zendesk.com/agent/tickets/";
const POCKET_COLLECTION_ZENDESK_TICKETS = "zendesk_tickets";

const POCKET_COLLECTION_ADMIN_SETTINGS = "admin_settings";

const ZENDESK_ASSIGNEE_ID_JUSTIN = "35387898477463";
const DISCORD_ID_JUSTIN = "90909125164163072";

const POCKET_ADMIN_IGNORE_DUPLICATE_ZENDESK_CALLBACK_IN_SECONDS = "IGNORE_DUPLICATE_ZENDESK_CALLBACK_IN_SECONDS";

module.exports = {
    POCKET_BLOGPOSTS,
    POCKET_ZENDESKUSER_DISCORDUSER,
    POCKET_SLA_BREACHING_SOON,
    DISCORD_API_ENDPOINT,
    ZENDESK_API_ENDPOINT,
    POCKET_COLLECTION_ZENDESK_TICKETS,
    ZENDESK_ASSIGNEE_ID_JUSTIN,
    DISCORD_ID_JUSTIN,
    POCKET_COLLECTION_ADMIN_SETTINGS,
    POCKET_ADMIN_IGNORE_DUPLICATE_ZENDESK_CALLBACK_IN_SECONDS
}