POCKET_BLOGPOSTS = "blogposts"
const POCKET_ZENDESKUSER_DISCORDUSER = "zendeskuser_discorduser"
const POCKET_SLA_BREACHING_SOON = "nearing_sla_breach_notified"
const DISCORD_API_ENDPOINT = "https://zen.jkim.win/api/discord/send-dm/";
const ZENDESK_API_ENDPOINT = "https://yaksa.zendesk.com/agent/tickets/";
const POCKET_COLLECTION_ZENDESK_TICKETS = "zendesk_tickets";

const POCKET_COLLECTION_ADMIN_SETTINGS = "admin_settings";
const POCKET_COLLECTION_ZENDESK_ORGANIZATIONS = "zendesk_organizations";

const ZENDESK_CLOSED_STATUS = "CLOSED";
const ZENDESK_SOLVED_STATUS = "SOLVED";
const ZENDESK_STATUS_CHANGED_TYPE = "zen:event-type:ticket.status_changed";
const ZENDESK_TICKET_CREATED = "zen:event-type:ticket.created";

const ZENDESK_ASSIGNEE_ID_JUSTIN = "35387898477463";
const DISCORD_ID_JUSTIN = "90909125164163072";

const POCKET_ADMIN_IGNORE_DUPLICATE_ZENDESK_CALLBACK_IN_SECONDS = "IGNORE_DUPLICATE_ZENDESK_CALLBACK_IN_SECONDS";
const POCKET_ADMIN_MAX_RANDOM_DELAY_IN_SECONDS = "MAX_RANDOM_DELAY_IN_SECONDS";
const POCKET_ADMIN_DISCORD_BOT_TOKEN = "SECRET_DISCORD_BOT_TOKEN";


module.exports = {
    POCKET_BLOGPOSTS,
    POCKET_ZENDESKUSER_DISCORDUSER,
    POCKET_SLA_BREACHING_SOON,
    DISCORD_API_ENDPOINT,
    ZENDESK_API_ENDPOINT,
    POCKET_COLLECTION_ZENDESK_TICKETS,
    POCKET_COLLECTION_ADMIN_SETTINGS,
    POCKET_COLLECTION_ZENDESK_ORGANIZATIONS,
    ZENDESK_CLOSED_STATUS,
    ZENDESK_SOLVED_STATUS,
    ZENDESK_STATUS_CHANGED_TYPE,
    ZENDESK_TICKET_CREATED,
    ZENDESK_ASSIGNEE_ID_JUSTIN,
    DISCORD_ID_JUSTIN,
    POCKET_ADMIN_IGNORE_DUPLICATE_ZENDESK_CALLBACK_IN_SECONDS,
    POCKET_ADMIN_MAX_RANDOM_DELAY_IN_SECONDS,
    POCKET_ADMIN_DISCORD_BOT_TOKEN
}